server:
  port: 9901
  tomcat:
    uri-encoding: UTF-8


spring:
  rabbitmq:
    host: xbcs.f3322.net
    port: 5672
    username: bsoft
    password: bsoft@123
  redis:
    database: 0
    timeout: 3000ms
    host: 192.168.200.201
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  application:
    name: auth0
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
#  security:
#    user:
#      name: admin
#      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:9902/eureka
  #    register-with-eureka: false
  #    fetch-registry: false
  instance:
    instance-id: auth0-1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）这样如果配置了“lease-expiration-duration-in-seconds”此选项，表示距离上一次发送心跳之后等待下一次发送心跳的间隔时间，如果超过了此间隔时间，则认为该微服务已经宕机了。
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: auth0
  company.name: bsoft.com

# 解决服务端超时
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000
        readTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'

#项目编号

projectNumber : 1000010

